language: ruby
cache: bundler
bundler_args: --without development doc

before_install:
  - gem update --system
  - gem --version

rvm:
  - jruby-9.2.6.0
  - 2.3
  - 2.4
  - 2.5
  - 2.6

matrix:
  fast_finish: true

branches:
  only:
    - master
